import { useState, useEffect } from 'react';
import api from '../../services/api';
import LoadingSpinner from '../../components/common/LoadingSpinner';
import AISalesSummary from '../../components/ai/AISalesSummary';
import AISmartTips from '../../components/ai/AISmartTips';
import AIObservations from '../../components/ai/AIObservations';
import { HiOutlineSparkles, HiOutlineRefresh } from 'react-icons/hi';
import toast from 'react-hot-toast';

const AIInsights = () => {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const fetchInsights = async (isRefresh = false) => {
    if (isRefresh) setRefreshing(true);
    else setLoading(true);

    try {
      const res = await api.get('/shop/ai/insights');
      setInsights(res.data.insights);
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to load AI insights');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  if (loading) return <LoadingSpinner text="Generating AI insights..." />;

  return (
    <div>
      <div className="flex items-center justify-between mb-8">
        <div>
          <div className="flex items-center gap-2">
            <HiOutlineSparkles className="w-6 h-6 text-primary-600" />
            <h1 className="section-title">AI Business Insights</h1>
          </div>
          <p className="section-subtitle">AI-powered analysis of your shop performance</p>
        </div>
        <button
          onClick={() => fetchInsights(true)}
          disabled={refreshing}
          className="btn-secondary btn-sm flex items-center gap-2"
        >
          <HiOutlineRefresh className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`} />
          {refreshing ? 'Refreshing...' : 'Refresh'}
        </button>
      </div>

      {!insights ? (
        <div className="card p-12 text-center">
          <HiOutlineSparkles className="w-16 h-16 text-gray-200 mx-auto mb-4" />
          <h3 className="font-semibold text-gray-900">Unable to generate insights</h3>
          <p className="text-sm text-gray-500 mt-1">Please try again later.</p>
        </div>
      ) : (
        <div className="space-y-6">
          <AISalesSummary summary={insights.salesSummary} />

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <AISmartTips tips={insights.smartTips} />
            <AIObservations observations={insights.observations} />
          </div>

          <p className="text-xs text-gray-400 text-center">
            Insights are generated by AI based on your shop data. Results may vary.
          </p>
        </div>
      )}
    </div>
  );
};

export default AIInsights;
